addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.1.0")
//addSbtPlugin("com.lihaoyi" % "workbench" % "0.4.1")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.20.0")
//addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.15")
addSbtPlugin("org.scala-js" % "sbt-jsdependencies" % "1.0.2")